### ISSUE TITLE
Wheres the Micro SD Card Holder?

### ISSUE THREAD

**Issue by NicoleMaggard** [proveskit/flight_controller_board#12]
HELP! THE MICRO SD CARD HOLDER HAS GONE MISSING IN LEGO CITY!
ahem...
In all seriousness, the current micro sd card holder is not presently stocked by JLC, I suggest utilizing the following part as a replacement:
https://www.lcsc.com/product-detail/span-style-background-color-ff0-SD-span-span-style-background-color-ff0-Card-span-Memory-span-style-background-color-ff0-Card-span-Connector_MOLEX-5033981892_C428492.html

**Comment by Mikefly123** [comment]
@NicoleMaggard this was address in Commit #ec48e63.
