### ISSUE TITLE
Clock speed changes during runtime

### ISSUE THREAD

**Issue by TheSilentDefender** [proveskit/flight_controller_board#22]
Pico SDK enables dynamic adjustment of the clock speed at runtime. With some modifications to the board-specific files provided in CircuitPython, this functionality can be exposed on the Python side of the firmware.

This could potentially reduce power consumption when the clock speed is lowered during non-intensive periods of orbit.

**Comment by TheSilentDefender** [comment]
Branch flight_controller_board should have the updated board files for circuit python, and a new firmware file.

**Comment by Mikefly123** [comment]
# Power Consumption Test Procedure
1. Attach the RP2040 to a power supply
2. Measure the power consumption at various points

To change the clock frequency of the microcontroller use the following code block: 
```py 
import machine, microcontroller
microcontroller.cpu.frequency
machine.set_clock(INSERT CLOCK SPEED IN HZ)
microcontroller.cpu.frequency
```
We need to collect data at the following points: 
| Clock Speed (MHz) | Sample 1 (mW) | Sample 2 (mW) | Sample 3 (mW) | Sample 4 (mW) |
|-------------------|---------------|---------------|---------------|---------------|
| 125               |               |               |               |               |
| 100               |               |               |               |               |
| 75                |               |               |               |               |
| 50                |               |               |               |               |
| 25                |               |               |               |               |

**Comment by wrong-formatt** [comment]
Power supply used: Korad KA3005P Programmable DC POwer Supply. 
Units of precision: Amps to 3 decimal places
Datatable will be updated


| Clock Speed (MHz) | Sample 1 (mW) | Sample 2 (mW) | Sample 3 (mW) | Sample 4 (mW) |
|-------------------|---------------|---------------|---------------|---------------|
| 125               |        151.8       |     125.4          |               |               |
| 100               |       151.8        |     125.4        |               |               |
| 75                |       151.8        |      125.4        |               |               |
| 62.5             |      118.8         |      89.1          |               |               |
| 50                |       115.5        |      85.8        |               |               |
| 25                |       102.3        |       72.6        |               |               |
| 12                |       99             |      69.3         |               |               |
| 1                  |       89.1          |       62.7        |               |               |

**Comment by Mikefly123** [comment]
Graphed by Claude: 
<img width="787" alt="Screenshot 2024-10-11 at 7 22 13 PM" src="https://github.com/user-attachments/assets/ec3cd986-9234-4686-b9f6-011e3c8be258">

**Comment by Mikefly123** [comment]
Closing this for now and continuing to track clock speed stuff in the linked flight software repo!
