### ISSUE TITLE
InspireFly Special Watchdog Interval is Unexpectedly Fast

### ISSUE THREAD

**Issue by Mikefly123** [proveskit/flight_controller_board#24]
# Description of the Issue
When biased with a 5V inout from a bench top PSU the watchdog appears to reset every 5 seconds when not being pet rather than the expected 26s. We are investigating this further.

**Comment by Mikefly123** [comment]
Just spoke with Andrew Greenberg and the apparent culprit it BOM consolidation! 
![image](https://github.com/user-attachments/assets/c8e64829-5e56-4822-b8f9-d6cae012640a)
Specifically, the D7 diode in the watchdog circuit was consolidated to be a common Schottky Diode in the InspireFly special and the voltage leakage through it is what is most likely changing the period of the oscillator. A note has been added to the schematic that we CANNOT consolidate the BOM on this sheet.

**Comment by polygnomial** [comment]
👀

**Comment by Mikefly123** [comment]
Closing this issue for now, it will be fixed on V5 Flight Controller Boards!
